#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "Adicity"
short_name = "adicity"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = "A fixed-arity high level functional programming language engine."
description = "A fixed-arity high level functional programming language engine."
url = "https://github.com/cole-wilson/adicity"
keywords = ""
license = "none"
latest_build = "0.6.4"
release-notes = "A"
latest_release = "0.6.3"


# Resource Setup:
[resources]
icns = ""
data_files = [ "*.p", "*.txt",]
modules = [ "colorama",]
file = "main.py"
no_import = [ "datetime", "inspect", "re", "os", "threading", "logging",]


# Plugin Commands:
[command.tasks]


# Build Routines:
[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.colewilson.adicity"

[build.actions]

[build.pypi.commands]
adicity = "adicity.main"

[build.pypi.entry_points]


# Release Routines:


# Other:
[git]


# Thank you for using Sailboat!